### ISSUE TITLE
Cannot install latest command line tool (> v1.1.0)

### ISSUE THREAD

**Issue by abarani** [lestrrat-go/jwx#349]
**Describe the bug**

Invalid go.mod file when trying to install the command line tool.

```bash
$ go version
go version go1.16 linux/amd64

$ go install github.com/lestrrat-go/jwx/cmd/jwx@v1.1.4
go install github.com/lestrrat-go/jwx/cmd/jwx@v1.1.4: module github.com/lestrrat-go/jwx@v1.1.4 found, but does not contain package github.com/lestrrat-go/jwx/cmd/jwx

$ go install github.com/lestrrat-go/jwx/cmd/jwx@latest
go: downloading github.com/lestrrat-go/jwx/cmd/jwx v0.0.0-20210301215237-a5ae64090aa8
go install github.com/lestrrat-go/jwx/cmd/jwx@latest: github.com/lestrrat-go/jwx/cmd/jwx@v0.0.0-20210301215237-a5ae64090aa8
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Additional context**

The latest tag that works is v1.1.0, the latest one without a go.mod file in it.
It is also the latest version reported on pkg.go.dev: https://pkg.go.dev/github.com/lestrrat-go/jwx/cmd/jwx

**Comment by lestrrat** [comment]
Looks like it has a stray replace directive placed at debug time.
I released a v1.1.5-rc1 so that you can call `go install github.com/lestrrat-go/jwx/cmd/jwx@latest`

pkg.go.dev is confused. It doesn't know how to distinguish subdirectories with go.mod

**Comment by abarani** [comment]
Thank you for your fast response!

I confirm it now works correctly with `go install github.com/lestrrat-go/jwx/cmd/jwx@latest`:
```bash
$ go install github.com/lestrrat-go/jwx/cmd/jwx@latest
go: downloading github.com/lestrrat-go/jwx/cmd/jwx v0.0.0-20210302221912-c9a7b177e98d
go: downloading github.com/urfave/cli/v2 v2.3.0
go: downloading github.com/lestrrat-go/pdebug/v3 v3.0.1
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
go: downloading github.com/russross/blackfriday/v2 v2.0.1
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
```

Problem is still present with specific versions though:
```bash
$ go install github.com/lestrrat-go/jwx/cmd/jwx@v1.1.5-rc1
go: downloading github.com/lestrrat-go/jwx v1.1.5-rc1
go install github.com/lestrrat-go/jwx/cmd/jwx@v1.1.5-rc1: module github.com/lestrrat-go/jwx@v1.1.5-rc1 found, but does not contain package github.com/lestrrat-go/jwx/cmd/jwx

$ go get github.com/lestrrat-go/jwx/cmd/jwx@v1.1.5-rc1
go get: module github.com/lestrrat-go/jwx@v1.1.5-rc1 found, but does not contain package github.com/lestrrat-go/jwx/cmd/jwx
```

**Comment by lestrrat** [comment]
@abarani I actually haven't investigated into why the behavior is such that @latest works but not with versions. I figured @latest or @commit-ish should do. Patches welcome :)

Closing this for now.
